# Generated by Django 5.2.7 on 2025-10-31 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('duracion', models.PositiveIntegerField(help_text='Duración en días')),
                ('puede_reservar_talleres', models.BooleanField(default=False)),
                ('puede_reservar_canchas', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlanBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='planes.plan')),
            ],
        ),
        migrations.CreateModel(
            name='SocioPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecInicio', models.DateField()),
                ('fecFin', models.DateField()),
                ('monto_pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes.plan')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_asignados', to='socios.socio')),
            ],
        ),
    ]
