# Generated by Django 5.2.7 on 2025-10-18 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion', models.IntegerField(help_text='Duración del plan en días')),
                ('fecCreacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='planes.plan')),
            ],
        ),
    ]
