# Generated by Django 5.2.7 on 2025-10-18 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocioPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecInicio', models.DateField()),
                ('fecFin', models.DateField()),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes.plan')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_asignados', to='clientes.socio')),
            ],
        ),
    ]
