# Generated by Django 5.2.7 on 2025-11-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duracion',
            field=models.PositiveIntegerField(help_text='Duración (días)'),
        ),
        migrations.AlterField(
            model_name='socioplan',
            name='monto_pagado',
            field=models.IntegerField(default=0, verbose_name='Monto Pagado'),
        ),
    ]
