# Generated by Django 5.2.7 on 2025-10-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_socioplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='fecCreacion',
        ),
        migrations.AddField(
            model_name='plan',
            name='puede_reservar_canchas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='puede_reservar_talleres',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duracion',
            field=models.PositiveIntegerField(help_text='Duración en días'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
