# Generated by Django 5.2.7 on 2025-10-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0003_remove_plan_feccreacion_plan_puede_reservar_canchas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socioplan',
            name='monto_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
