# Generated by Django 5.2.7 on 2025-11-03 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id_taller', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cupos', models.PositiveIntegerField(default=10)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('profesor', models.ForeignKey(limit_choices_to={'rol': 'profesor'}, on_delete=django.db.models.deletion.PROTECT, related_name='talleres_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Taller',
                'verbose_name_plural': 'Talleres',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('inscrito', 'Inscrito'), ('cancelado', 'Cancelado')], default='inscrito', max_length=10)),
                ('asistencia', models.CharField(choices=[('pendiente', 'Pendiente'), ('presente', 'Presente'), ('ausente', 'Ausente')], default='pendiente', max_length=10)),
                ('fec_registro', models.DateTimeField(auto_now_add=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_taller', to='socios.socio')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='talleres.taller')),
            ],
            options={
                'verbose_name': 'Inscripción a Taller',
                'verbose_name_plural': 'Inscripciones a Talleres',
                'ordering': ['-fec_registro'],
                'unique_together': {('socio', 'taller')},
            },
        ),
    ]
