# Generated by Django 5.2.7 on 2025-10-19 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('basket', 'Básquetbol'), ('volley', 'Vóleibol'), ('futbol', 'Fútbol Sala'), ('tenis', 'Tenis'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cupos', models.PositiveIntegerField(default=10)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('profesor', models.ForeignKey(limit_choices_to={'rol': 'profesor'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ReservaCancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('reservada', 'Reservada'), ('cancelada', 'Cancelada')], default='reservada', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.cancha')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_cancha', to='clientes.socio')),
            ],
            options={
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('inscrito', 'Inscrito'), ('cancelado', 'Cancelado')], default='inscrito', max_length=10)),
                ('fec_registro', models.DateTimeField(auto_now_add=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='reservas.clase')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_clase', to='clientes.socio')),
            ],
            options={
                'ordering': ['-fec_registro'],
                'unique_together': {('socio', 'clase')},
            },
        ),
    ]
