# Generated by Django 5.2.7 on 2025-10-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancha',
            options={},
        ),
        migrations.RenameField(
            model_name='cancha',
            old_name='activo',
            new_name='activa',
        ),
        migrations.AddField(
            model_name='cancha',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cancha',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='tipo',
            field=models.CharField(choices=[('futbol', 'Fútbol'), ('tenis', 'Tenis'), ('pádel', 'Pádel'), ('multiuso', 'Multiuso'), ('otro', 'Otro')], default='multiuso', max_length=20),
        ),
    ]
