# Generated by Django 5.2.7 on 2025-10-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionclase',
            name='asistencia',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('asistio', 'Asistió'), ('ausente', 'Ausente')], default='pendiente', max_length=10),
        ),
    ]
