# Generated by Django 5.2.7 on 2025-10-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_cancha_options_rename_activo_cancha_activa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancha',
            options={'ordering': ['nombre'], 'verbose_name': 'Cancha', 'verbose_name_plural': 'Canchas'},
        ),
        migrations.RemoveField(
            model_name='cancha',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='cancha',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='cancha',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='cancha',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='tipo',
            field=models.CharField(choices=[('basket', 'Básquetbol'), ('volley', 'Vóleibol'), ('futbol', 'Fútbol'), ('tenis', 'Tenis')], default='otro', max_length=20),
        ),
    ]
