# Generated by Django 5.2.7 on 2025-10-20 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_reserva_delete_reservacancha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcionclase',
            name='asistencia',
        ),
        migrations.CreateModel(
            name='ClaseRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Spinning, Yoga, Zumba', max_length=100)),
                ('cupos', models.PositiveIntegerField(default=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('fec_inicio', models.DateField()),
                ('fec_fin', models.DateField()),
                ('repetir_diario', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('profesor', models.ForeignKey(limit_choices_to={'rol': 'profesor'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clase Recurrente',
                'verbose_name_plural': 'Clases Recurrentes',
                'ordering': ['-fec_inicio', 'nombre'],
            },
        ),
    ]
