# Generated by Django 5.2.7 on 2025-10-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_remove_inscripcionclase_asistencia_claserecurrente'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionclase',
            name='asistencia',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('presente', 'Presente'), ('ausente', 'Ausente')], default='pendiente', max_length=10),
        ),
    ]
