# Generated by Django 5.2.7 on 2025-10-20 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_inscripcionclase_asistencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancha',
            options={'ordering': ['nombre'], 'verbose_name': 'Cancha', 'verbose_name_plural': 'Canchas'},
        ),
        migrations.AlterModelOptions(
            name='clase',
            options={'ordering': ['fecha', 'hora_inicio'], 'verbose_name': 'Clase', 'verbose_name_plural': 'Clases'},
        ),
        migrations.AlterModelOptions(
            name='inscripcionclase',
            options={'ordering': ['-fec_registro'], 'verbose_name': 'Inscripción a Clase', 'verbose_name_plural': 'Inscripciones a Clases'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha', 'hora_inicio'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.DeleteModel(
            name='ClaseRecurrente',
        ),
    ]
