# Generated by Django 5.2.7 on 2025-10-31 03:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecNac', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('estado', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True)),
                ('fec_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
