# Generated by Django 5.2.7 on 2025-11-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altura en metros', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='objetivo',
            field=models.CharField(choices=[('bajar_peso', 'Bajar de peso'), ('subir_masa', 'Subir masa muscular'), ('bajar_grasa', 'Reducir grasa corporal'), ('mantener', 'Mantener condición física'), ('aumentar_fuerza', 'Aumentar fuerza'), ('mejorar_resistencia', 'Mejorar resistencia / Cardio'), ('mejorar_flexibilidad', 'Mejorar flexibilidad / Movilidad'), ('rendimiento_deportivo', 'Mejorar rendimiento deportivo'), ('salud_bienestar', 'Salud y bienestar / Reducir estrés'), ('rehabilitacion', 'Rehabilitación / Recuperación de lesión'), ('tonificar', 'Tonificar / Definir')], default='mantener', max_length=40),
        ),
        migrations.AddField(
            model_name='socio',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kilogramos', max_digits=5, null=True),
        ),
    ]
