# Generated by Django 5.2.7 on 2025-11-09 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_socio_altura_socio_objetivo_socio_peso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='profesor_asignado',
            field=models.ForeignKey(blank=True, help_text='Profesor asignado a este socio', limit_choices_to={'rol': 'profesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
