# Generated by Django 5.2.7 on 2025-11-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('zumba', 'Zumba'), ('spinning', 'Spinning'), ('pilates', 'Pilates'), ('yoga', 'Yoga'), ('pesas', 'Pesas / Musculación'), ('cardio', 'Cardio / Resistencia'), ('funcional', 'Entrenamiento Funcional')], help_text='Área de especialización del profesor', max_length=30, null=True),
        ),
    ]
