# Generated by Django 5.2.7 on 2025-11-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='especialidad',
            field=models.CharField(choices=[('no_aplica', 'No aplica'), ('zumba', 'Zumba'), ('spinning', 'Spinning'), ('pilates', 'Pilates'), ('yoga', 'Yoga'), ('pesas', 'Pesas / Musculación'), ('cardio', 'Cardio / Resistencia'), ('funcional', 'Entrenamiento Funcional')], default='no_aplica', help_text='Área de especialización del profesor', max_length=30),
        ),
    ]
