# Generated by Django 5.2.7 on 2025-11-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.IntegerField(verbose_name='Monto'),
        ),
    ]
