# Generated by Django 5.2.7 on 2025-11-09 20:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0002_socio_altura_socio_objetivo_socio_peso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RutinaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('objetivo', models.CharField(choices=[('bajar_peso', 'Bajar de peso'), ('subir_masa', 'Subir masa muscular'), ('bajar_grasa', 'Reducir grasa corporal'), ('mantener', 'Mantener condición física'), ('aumentar_fuerza', 'Aumentar fuerza'), ('mejorar_resistencia', 'Mejorar resistencia / Cardio'), ('mejorar_flexibilidad', 'Mejorar flexibilidad / Movilidad'), ('rendimiento_deportivo', 'Mejorar rendimiento deportivo'), ('salud_bienestar', 'Salud y bienestar / Reducir estrés'), ('rehabilitacion', 'Rehabilitación / Recuperación de lesión'), ('tonificar', 'Tonificar / Definir')], max_length=40)),
                ('imc_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imc_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contenido', models.TextField(help_text='Detalle de la rutina predefinida')),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ejemplo: Rutina fuerza y resistencia - Semana 1', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción general de los objetivos de esta rutina.', null=True)),
                ('contenido', models.TextField(help_text='Detalle completo de la rutina: ejercicios, repeticiones, descansos, observaciones.')),
                ('imc_referencia', models.DecimalField(blank=True, decimal_places=2, help_text='IMC del socio al momento de crear la rutina (para referencia o automatización futura).', max_digits=5, null=True)),
                ('archivo_pdf', models.FileField(blank=True, help_text='Archivo PDF generado automáticamente.', null=True, upload_to='rutinas/pdf/')),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=10)),
                ('profesor', models.ForeignKey(limit_choices_to={'rol': 'profesor'}, on_delete=django.db.models.deletion.PROTECT, related_name='rutinas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas_recibidas', to='socios.socio')),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'ordering': ['-fecha_asignacion'],
                'unique_together': {('profesor', 'socio', 'titulo')},
            },
        ),
    ]
