# Generated by Django 5.2.7 on 2025-11-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rutina',
            options={'ordering': ['-fecha_asignacion']},
        ),
        migrations.AlterField(
            model_name='rutina',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='rutinas/pdf/'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='imc_referencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rutinabase',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rutinabase',
            name='objetivo',
            field=models.CharField(choices=[('bajar_peso', 'Bajar de peso'), ('subir_masa', 'Subir masa muscular'), ('bajar_grasa', 'Reducir grasa corporal'), ('mantener', 'Mantener condición física'), ('aumentar_fuerza', 'Aumentar fuerza'), ('tonificar', 'Tonificar / Definir')], max_length=40),
        ),
    ]
